name: ModPacker

on:
  workflow_dispatch:
    inputs:
      modpack_name:
        description: "模組包名稱"
        required: false
        default: "Caveopolis"
      modpack_version:
        description: "模組包版本"
        required: false
        default: "v1.0"
      tag:
        description: "發布版本，例如 v1.0（如果為空，將只會生成開發版）"
        required: false
        default: "開發版"

permissions:
  contents: write

jobs:
  ModPack:
    name: 製作模組包補丁
    runs-on: ubuntu-latest

    steps:
      - name: 查看專案
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 執行製作補丁的腳本
        env: 
          VERSION: ${{ github.event.inputs.tag }}
        run: bash .github/scripts/ModPacker.sh

      - name: 上傳模組包補丁壓縮檔
        uses: actions/upload-artifact@v3
        with:
          name: 模組包補丁壓縮檔
          path: "*.zip"

  ModsResourcePack:
    name: 製作模組資源包
    runs-on: ubuntu-latest

    steps:
      - name: 查看專案
        uses: actions/checkout@v3
        with:
          ref: resoucepack
          fetch-depth: 0
      
      - name: 自動更新版本
        run: |
          sed -i 's/$VERSION/'${{ github.event.inputs.tag }}'/1' pack.mcmeta

      - name: 製作模組中文化資源包
        uses: ComunidadAylas/PackSquash-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          force_include_files: |
            LICENSE
          never_store_squash_times: true
          path: ./

      - name: 下載壓縮檔
        uses: actions/download-artifact@v2
        with:
          name: Optimized pack
          path: ./

      - name: 刪除 Artifact
        uses: geekyeggo/delete-artifact@v1
        with:
          name: |
            Optimized pack

      - name: 重新命名壓縮檔
        run: |
          mv ./pack.zip ${{ github.event.inputs.modpack_name}}-Mods-Localization-${{ github.event.inputs.tag }}.zip

      - name: 上傳模組中文化資源包
        uses: actions/upload-artifact@v3
        with:
          name: 模組中文化資源包
          path: "*.zip"

  ModPack-Release:
    needs: [ ModPack, ModsResourcePack ]
    if: "${{ github.event.inputs.tag != '開發版' }}"
    name: 發布模組包
    runs-on: ubuntu-latest

    steps:
      - name: 下載所有壓縮檔
        uses: actions/download-artifact@v3

      - name: 移動檔案到主工作資料夾
        run: |
          mv 模組包補丁壓縮檔/*.zip .
          mv 模組中文化資源包/*.zip .

      - name: 創建發布
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.event.inputs.modpack_name}} 中文化翻譯 ${{ github.event.inputs.tag }}
          tag_name: ${{ github.event.inputs.tag }}
          files: "*.zip"
          body: |
            ## ${{ github.event.inputs.modpack_name}} 模組包版本 ${{ github.event.inputs.modpack_version }}

            ## 下載安裝
            請下載下方的 ``${{ github.event.inputs.modpack_name}}-Patches.zip`` 與 ``${{ github.event.inputs.modpack_name}}-Mods-Localization-${{ github.event.inputs.tag }}.zip``

            ## 模組包中文化補丁
            使用 7-Zip 等軟體開啟 ``${{ github.event.inputs.modpack_name}}-Patches.zip`` 壓縮檔，並將壓縮檔中的內容，解壓縮到模組包的 ``.minecraft`` 資料夾

            ## 模組中文化資源包
            將 ``${{ github.event.inputs.modpack_name}}-Mods-Localization-${{ github.event.inputs.tag }}.zip`` 放入模組包的 ``resourcepacks`` 資料夾，並在遊戲中選取並載入
